sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LhWTAw2+B24cJXRGtwYOvDq4r1iMlxfRp5TK0ozzjjgW2ADCNBGDj3iZHYtVZmz7ihTD1QAi3kZVqbfQOfJqzkPDZ9vx8umBRPkFeLLmDeSMu9//5AnOhASxjE7cDr8m7ou4cZVy+tPmzKv1MjawATWDobvaZcXC4cgCJ0y5kZx2RGUaX7sFDrFDcbxKJ5FNK483SAWMNPlBkaSgJkKi+JpvNU+rfjMxn3ZR2dO9SpV3RSEs5thaE14ojmJIOtg5pspH+ZfeT+JtrZt12S/2C7mSWbd4n27YOQRD8VOKCZqKCjILun5tmCoJLJiQRz7gy5MjZ/4Y6F+7C9htXVG5gyDRF+H2V6OamPlHPhrqjRS5kft2KpI1vDj+LI9znkCfKCfEPJsYu2VtA10nS+jEQO53nU/ryzN1DZdh9DPDosXIX0HkpK2VJup/2JUCWCk6m0MRzpZ1PWJxsLwBFcdAlqB5zioOlbqhycMxAZZzEIRAPzOTwU/YeYRLeHrkYxCZComLsWU68UCNZUA/Beaong7IqCEZWgXym/70MG+Cgl2n1sNj+dBjvUykSn98mjWdrKN8MQgtjH1biF6xlr6QEjAo9r8kUuXWto1b4bsRUdZuP+xGcX0kkwsPrpGidL5vjECtHlprOHvkxFkfdKSucQgW8Pa89gWnNQ5W0ARvEf8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Story-of-Sonny-Sahib_4547
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy